from .condenser_prompts import get_condenser_template, get_simple_condenser_template
from .detection_prompts import get_detection_template
from .explainer_prompts import get_explainer_template, get_simple_explainer_template
from .gen_scorer_prompts import get_gen_scorer_template