from collections import defaultdict

class History():

    def __init__(self):
        self.history = defaultdict(lambda: defaultdict(dict))

    def add(
        self,
        id: int,
        turn: dict,
        round: int
    ): 
        # A turn is a dictionary with keys "user" and "assisstant" 
        # these correspond to the prompt passed to the agent and
        # the response generated by the agent
        self.history[id][round] = turn

    def get_other_responses(
        self,
        id: int,
        round: int
    ) -> list:
        round_responses = self.get_round(round)
        return {id: response for id, response in round_responses.items() if id != id}
    
    def get_round(
        self,
        round: int
    ) -> list:
        return {id: response[round] for id, response in self.history.items()}